export const TAG_ANY_PLAYER = "TAG_ANY_PLAYER";
export const TAG_MOBLIN_ROAM_POINT = "TAG_MOBLIN_ROAM_POINT";
export const TAG_PLAYER_WEAPON = "TAG_PLAYER_WEAPON";
export const TAG_DAMAGES_PLAYER = "TAG_DAMAGES_PLAYER";
export const TAG_ANY_ENEMY = "TAG_ANY_ENEMY";